name: v1-hdmi-zero2w
on: workflow_dispatch


jobs:
  os:
    uses: pikvm/os/.github/workflows/os.yml@test
    with:
      BOARD: zero2w
      PLATFORM: v1-hdmi
    secrets:
      DEPLOY_KEY: "${{secrets.DEPLOY_KEY}}"
